### ISSUE TITLE
using `cp -r` to copy externals doesn't preserve internal symlinks

### ISSUE THREAD

**Issue by shakfu** [Cycling74/max-package-template#1]
Hi,

Thanks for this template repo!

I was just reading through the `main.yml` workflow and I noted that you were using `cp -r` to copy external bundles for `macos` platforms:

```bash
if [ -d externals ]; then cp -r externals $PACKAGE_NAME; fi
```

I'm not sure this is best practice. The use of `cp -r` is discouraged per se, but particularly problematic for bundles which are likely to contain symlinks (if they are non-trivial). 

See this text at the bottom of  the macos `cp` man file:

```text
COMPATIBILITY
     Historic versions of the cp utility had a -r option.  This implementation
     supports that option; however, its use is strongly discouraged, as it
     does not correctly copy special files, symbolic links, or fifo's.
```

As a suggestion, it's probably better to use `cp -a` or `ditto` to preserve symlinks and / or code signatures.

**Comment by isabelgk** [comment]
Thanks for the tip!
